# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH="$PATH:$HOME/.local/bin"

plugins=(git)
. "$HOME/.cargo/env"
zstyle :compinstall filename '/home/kautsar/.zshrc'
source $ZSH/oh-my-zsh.sh

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


alias ls='eza --icons=auto'
alias ll='ls -lhA'
alias cte='chmod 755'
alias grep='grep --color=auto'
alias update='sudo pacman -Syu'
alias install='sudo pacman -S'

precmd() {
  PROMPT=$' %F{yellow}%*%f %F{blue} \uf015 type here %~\n%f %F{green}$%f '

}
autoload -Uz compinit
compinit

## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[[ -f /home/kautsar/.dart-cli-completion/zsh-config.zsh ]] && . /home/kautsar/.dart-cli-completion/zsh-config.zsh || true

## [/Completion]

