# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH="$PATH:$HOME/.local/bin"

zstyle :compinstall filename '$HOME/.zshrc'
source $ZSH/oh-my-zsh.sh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

alias ls='eza --icons=auto'
alias ll='ls -lhA'
alias cte='chmod 755'
alias grep='grep --color=auto'
alias empty="echo '' >"

git_branch_name() {
  branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
  if [[ $branch == "" ]];
  then
    :
  else
    echo '- ('$branch')'
  fi
}

precmd() {
  PROMPT=$' %F{yellow}%*%f %F{blue} \uf015 tsarcasticx %~ $(git_branch_name)\n%f %F{green}$%f '

}
autoload -Uz compinit
compinit
