[colors]
wheat-light = #cecbb0
purple = #eaafb9
grey = #4d4d4d
lavender = #6c71c4

[module/workspaces]
type = internal/bspwm
enable-click = true
enable-scroll = true

ws-icon-0 = I;一 
ws-icon-1 = II;  二 
ws-icon-2 = III;  三 
ws-icon-3 = IV;  四 
ws-icon-4 = V;  五 
ws-icon-5 = VI;  六 
ws-icon-6 = VII;  七 
ws-icon-7 = VIII;  八 
ws-icon-8 = IX;  九 
ws-icon-9 = X;  零

label-focused = %icon%
label-focused-foreground = ${colors.purple}

label-occupied = %icon%
label-occupied-foreground = ${colors.wheat-light}

label-empty= %icon%
label-empty-foreground = ${colors.grey}

; you might not be able to click-left it, so leave it a comment or just delete it
[module/power]
type = custom/text
content = "⏻ "
content-foreground = ${colors.lavender}
click-left = $HOME/./.config/polybar/scripts/powermenu.sh

[module/terminal]
type = custom/text
content = " "
click-left = kitty
click-right = kitty nvim
content-foreground = ${colors.lavender}

[module/folder]
type = custom/text
content = " "
click-left = thunar
content-foreground = ${colors.lavender}

[module/volume]
type = internal/pulseaudio
use-ui-max = false
click-right = pavucontrol

label-muted = "󰝟"
format-volume = <ramp-volume>
format-volume-foreground = ${colors.lavender}

ramp-volume-0 = "󰸈 "
ramp-volume-1 = "󰖀 "
ramp-volume-2 = "󰕾 "

[module/net]
type = internal/network
interface = wlan0
interface-type = wireless
interval = 3

label-disconnected = "%{A1:nmcli device connect wlp3s0:}󰤮%{A}"
label-disconnected-foreground = ${colors.lavender}
format-connected =" %{A1:nmcli device disconnect wlp3s0:}<ramp-signal>%{A}"
format-connected-foreground = ${colors.lavender}
format-packetloss = "%{A1:nmcli device disconnect wlp3s0:}<animation-packetloss> ON%{A}"
format-packetloss-foreground = ${colors.lavender}

ramp-signal-0 = "󰤨"
ramp-signal-1 = "󰤢"
ramp-signal-2 = "󰤟"

animation-packetloss-0 = "󰅛"
animation-packetloss-1 = " "
animation-packetloss-framerate = 1000

; and also this module. Leave a comment or delete.
[module/rofi]
type = custom/text
content = ""
click-left = rofi -modi drun -show drun -line-padding 4 -columns 2 -padding 50 -hide-scrollbar -terminal xfce4-terminal -show-icons -drun-icon-theme "Qogir-dark" -font "Droid Sans Regular 10"
content-foreground = ${colors.lavender}
content-padding = 1
margin-right = 0

[module/title]
type = internal/xwindow
format = <label>
format-foreground = ${colors.lavender}
format-padding = 4

label = "%title%"
label-maxlen = 20

label-empty = "tsarcasticx"
label-empty-foreground = ${colors.lavender}

[bar/wmtitle]
wm-restack = bspwm
monitor = HDMI-1
bottom = true
fixed-center = true
height = 36
width = 260
offset-x = 1045
offset-y = 16
background = ${colors.wheat-light}
font-0 ="Baskervville:style=Bold:size=14;2"
modules-center = title

[bar/bottom]
override-redirect = false
wm-restack = bspwm
monitor = HDMI-1
bottom = true
fixed-center = true
height = 36
width = 240
offset-x = 570
offset-y = 16
background = ${colors.wheat-light}
font-0 = "JetBrainsMonoNL NF ExtraBold:style=ExtraBold:size=20;6"
modules-center = power terminal folder volume net rofi

; top bar is necessary until I can config eww normally
[bar/top]
override-redirect = false
wm-restack = bspwm
monitor = HDMI-1
bottom = false
fixed-center = true
height = 36
width = 462
offset-x = 450
offset-y = 16
radius = 18
border-size = 6
border-color = ${colors.wheat-light}
background = ${colors.lavender}
font-0 = "Yuji Boku:style=Regular:size=18;6"
modules-center = workspaces
